corner-radius = 8;
shadow = true;
shadow-radius = 12;
shadow-opacity = 0.4;
shadow-offset-x = -8;
shadow-offset-y = -8;
fading = true;
fade-in-step = 0.05;
fade-out-step = 0.05;
inactive-opacity = 0.85;
active-opacity = 1.0;
backend = 'xrender';
glx-no-stencil = true;
